/**
 * 이벤트 관리 Mock 데이터
 */

import type { Event, EventParticipant } from '@/types/event';

export const mockEvents: Event[] = [
  {
    id: 'evt-1',
    eventType: 'participation',
    title: '여름 시즌 특별 할인 이벤트',
    description: '여름 시즌을 맞아 전 메뉴 20% 할인 프로모션',
    content: '<h2>여름 특별 할인!</h2><p>무더운 여름을 시원하게 즐기세요. <strong>전 메뉴 20% 할인</strong> 이벤트를 진행합니다.</p><ul><li>기간: 7월 1일 ~ 8월 31일</li><li>대상: 앱 회원 전체</li></ul>',
    bannerImageUrl: 'https://placehold.co/800x400/FFD700/333?text=Summer+Sale',
    detailImageUrl: 'https://placehold.co/800x1200/FFD700/333?text=Summer+Detail',
    status: 'active',
    eventStartDate: '2026-07-01T00:00',
    eventEndDate: '2026-08-31T23:59',
    publishDate: null,
    deepLink: 'myapp://events/evt-1',
    promoLink: 'https://promo.cnttech.co.kr/events/evt-1',
    orderButtonEnabled: true,
    orderButtonLabel: '할인 메뉴 보러가기',
    orderButtonLink: 'myapp://menu?discount=summer',
    shareButtonEnabled: true,
    shareChannels: ['kakao', 'facebook', 'link_copy'],
    shareTitle: '여름 특별 할인 20%!',
    shareDescription: '전 메뉴 20% 할인 이벤트 진행 중! 지금 바로 주문하세요.',
    shareImageUrl: 'https://placehold.co/600x315/FFD700/333?text=Share',
    collectionMode: 'auto',
    formFields: [],
    consentRequired: true,
    thirdPartyConsentRequired: false,
    consentText: '개인정보 수집 및 이용에 동의합니다.',
    thirdPartyConsentText: '',
    stats: {
      pageViews: 12450,
      uniqueVisitors: 8320,
      orderButtonClicks: 3210,
      shareCount: 890,
      participantCount: 5640,
      conversionRate: 25.8,
    },
    createdAt: '2026-06-20T10:00:00Z',
    updatedAt: '2026-07-05T14:30:00Z',
    createdBy: '김관리',
  },
  {
    id: 'evt-2',
    eventType: 'general',
    title: '신규 가입 환영 이벤트',
    description: '앱 신규 가입 시 5,000원 쿠폰 즉시 지급',
    content: '<h2>신규 가입 혜택</h2><p>앱을 처음 설치하시는 분께 <strong>5,000원 할인 쿠폰</strong>을 즉시 드립니다!</p>',
    bannerImageUrl: 'https://placehold.co/800x400/87CEEB/333?text=Welcome',
    detailImageUrl: '',
    status: 'active',
    eventStartDate: '2026-01-01T00:00',
    eventEndDate: '2026-12-31T23:59',
    publishDate: null,
    deepLink: 'myapp://events/evt-2',
    promoLink: 'https://promo.cnttech.co.kr/events/evt-2',
    orderButtonEnabled: true,
    orderButtonLabel: '주문하러 가기',
    orderButtonLink: 'myapp://menu',
    shareButtonEnabled: true,
    shareChannels: ['kakao', 'link_copy'],
    shareTitle: '신규 가입하면 5,000원 쿠폰!',
    shareDescription: '앱 가입 즉시 5,000원 쿠폰을 받으세요.',
    shareImageUrl: 'https://placehold.co/600x315/87CEEB/333?text=Welcome+Share',
    collectionMode: 'auto',
    formFields: [],
    consentRequired: false,
    thirdPartyConsentRequired: false,
    consentText: '',
    thirdPartyConsentText: '',
    stats: {
      pageViews: 34200,
      uniqueVisitors: 28100,
      orderButtonClicks: 8900,
      shareCount: 2100,
      participantCount: 0,
      conversionRate: 26.0,
    },
    createdAt: '2025-12-15T09:00:00Z',
    updatedAt: '2026-02-01T11:00:00Z',
    createdBy: '김관리',
  },
  {
    id: 'evt-3',
    eventType: 'participation',
    title: '봄맞이 스탬프 이벤트',
    description: '5회 주문 시 음료 1잔 무료 증정',
    content: '<h2>봄맞이 스탬프 이벤트</h2><p>기간 내 5회 주문하시면 인기 음료 1잔을 <strong>무료</strong>로 드립니다.</p><ol><li>앱에서 주문 시 자동 스탬프 적립</li><li>5개 모이면 무료 음료 쿠폰 자동 발급</li></ol>',
    bannerImageUrl: 'https://placehold.co/800x400/98FB98/333?text=Spring+Stamp',
    detailImageUrl: 'https://placehold.co/800x1200/98FB98/333?text=Stamp+Detail',
    status: 'scheduled',
    eventStartDate: '2026-03-01T00:00',
    eventEndDate: '2026-05-31T23:59',
    publishDate: '2026-02-25T09:00',
    deepLink: 'myapp://events/evt-3',
    promoLink: 'https://promo.cnttech.co.kr/events/evt-3',
    orderButtonEnabled: true,
    orderButtonLabel: '지금 주문하기',
    orderButtonLink: 'myapp://menu',
    shareButtonEnabled: true,
    shareChannels: ['kakao', 'facebook', 'twitter', 'link_copy'],
    shareTitle: '5번 주문하면 무료 음료!',
    shareDescription: '봄맞이 스탬프 이벤트에 참여하세요.',
    shareImageUrl: 'https://placehold.co/600x315/98FB98/333?text=Spring+Share',
    collectionMode: 'form_input',
    formFields: ['name', 'phone', 'email', 'address'],
    consentRequired: true,
    thirdPartyConsentRequired: true,
    consentText: '개인정보 수집 및 이용에 동의합니다.',
    thirdPartyConsentText: '개인정보 제3자 제공에 동의합니다.',
    stats: {
      pageViews: 0,
      uniqueVisitors: 0,
      orderButtonClicks: 0,
      shareCount: 0,
      participantCount: 0,
      conversionRate: 0,
    },
    createdAt: '2026-02-10T14:00:00Z',
    updatedAt: '2026-02-15T16:00:00Z',
    createdBy: '이정훈',
  },
  {
    id: 'evt-4',
    eventType: 'general',
    title: '크리스마스 한정 메뉴 출시',
    description: '12월 한정 크리스마스 시즌 메뉴',
    content: '<h2>크리스마스 한정 메뉴</h2><p>특별한 크리스마스 시즌 메뉴를 만나보세요!</p>',
    bannerImageUrl: 'https://placehold.co/800x400/FF6347/fff?text=Christmas',
    detailImageUrl: '',
    status: 'ended',
    eventStartDate: '2025-12-01T00:00',
    eventEndDate: '2025-12-31T23:59',
    publishDate: null,
    deepLink: 'myapp://events/evt-4',
    promoLink: 'https://promo.cnttech.co.kr/events/evt-4',
    orderButtonEnabled: true,
    orderButtonLabel: '메뉴 보기',
    orderButtonLink: 'myapp://menu?season=christmas',
    shareButtonEnabled: false,
    shareChannels: [],
    shareTitle: '',
    shareDescription: '',
    shareImageUrl: '',
    collectionMode: 'auto',
    formFields: [],
    consentRequired: false,
    thirdPartyConsentRequired: false,
    consentText: '',
    thirdPartyConsentText: '',
    stats: {
      pageViews: 22300,
      uniqueVisitors: 15400,
      orderButtonClicks: 6700,
      shareCount: 0,
      participantCount: 0,
      conversionRate: 30.0,
    },
    createdAt: '2025-11-20T10:00:00Z',
    updatedAt: '2026-01-02T09:00:00Z',
    createdBy: '김관리',
  },
  {
    id: 'evt-5',
    eventType: 'general',
    title: '설날 맞이 복주머니 이벤트',
    description: '설날 기간 랜덤 쿠폰 증정',
    content: '<h2>설날 복주머니</h2><p>설날 연휴 기간 앱 접속 시 랜덤 쿠폰을 드립니다!</p>',
    bannerImageUrl: 'https://placehold.co/800x400/FF4500/fff?text=Lunar+New+Year',
    detailImageUrl: '',
    status: 'scheduled',
    eventStartDate: '2026-01-25T00:00',
    eventEndDate: '2026-02-05T23:59',
    publishDate: null,
    deepLink: '',
    promoLink: '',
    orderButtonEnabled: true,
    orderButtonLabel: '주문하러 가기',
    orderButtonLink: '',
    shareButtonEnabled: true,
    shareChannels: ['kakao', 'link_copy'],
    shareTitle: '',
    shareDescription: '',
    shareImageUrl: '',
    collectionMode: 'auto',
    formFields: [],
    consentRequired: false,
    thirdPartyConsentRequired: false,
    consentText: '',
    thirdPartyConsentText: '',
    stats: {
      pageViews: 0,
      uniqueVisitors: 0,
      orderButtonClicks: 0,
      shareCount: 0,
      participantCount: 0,
      conversionRate: 0,
    },
    createdAt: '2026-02-18T15:00:00Z',
    updatedAt: '2026-02-18T15:00:00Z',
    createdBy: '이정훈',
  },
];

// 이벤트별 참여자 Mock 데이터
export const mockEventParticipants: EventParticipant[] = [
  // evt-1: 회원 자동수집 참여자
  { id: 'ep-1', eventId: 'evt-1', memberId: 'mem-101', memberName: '김민지', memberPhone: '010-1234-5678', memberEmail: 'minji@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-01T10:30:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'page_view' },
  { id: 'ep-2', eventId: 'evt-1', memberId: 'mem-102', memberName: '이준호', memberPhone: '010-2345-6789', memberEmail: 'junho@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-01T11:00:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'order_click' },
  { id: 'ep-3', eventId: 'evt-1', memberId: 'mem-103', memberName: '박소연', memberPhone: '010-3456-7890', memberEmail: 'soyeon@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-01T12:15:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'share' },
  { id: 'ep-4', eventId: 'evt-1', memberId: 'mem-104', memberName: '최현우', memberPhone: '010-4567-8901', memberEmail: 'hyunwoo@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-02T09:00:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'page_view' },
  { id: 'ep-5', eventId: 'evt-1', memberId: 'mem-105', memberName: '정하은', memberPhone: '010-5678-9012', memberEmail: 'haeun@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-02T10:30:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'order_click' },
  { id: 'ep-6', eventId: 'evt-1', memberId: 'mem-106', memberName: '한서진', memberPhone: '010-6789-0123', memberEmail: 'seojin@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-02T14:00:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'page_view' },
  { id: 'ep-7', eventId: 'evt-1', memberId: 'mem-107', memberName: '윤지호', memberPhone: '010-7890-1234', memberEmail: 'jiho@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-03T08:30:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'order_click' },
  { id: 'ep-8', eventId: 'evt-1', memberId: 'mem-108', memberName: '송예린', memberPhone: '010-8901-2345', memberEmail: 'yerin@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-03T11:45:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'share' },
  { id: 'ep-9', eventId: 'evt-1', memberId: 'mem-109', memberName: '강도윤', memberPhone: '010-9012-3456', memberEmail: 'doyun@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-04T09:00:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'page_view' },
  { id: 'ep-10', eventId: 'evt-1', memberId: 'mem-110', memberName: '임서현', memberPhone: '010-0123-4567', memberEmail: 'seohyun@example.com', memberAddress: '', collectionMode: 'auto', participatedAt: '2026-07-04T16:20:00Z', hasConsented: true, hasThirdPartyConsented: false, actionType: 'order_click' },
  // evt-3: 입력수집 참여자
  { id: 'ep-11', eventId: 'evt-3', memberId: null, memberName: '김민지', memberPhone: '010-1234-5678', memberEmail: 'minji@example.com', memberAddress: '서울시 강남구 역삼동 123-4', collectionMode: 'form_input', participatedAt: '2026-03-01T09:00:00Z', hasConsented: true, hasThirdPartyConsented: true, actionType: 'page_view' },
  { id: 'ep-12', eventId: 'evt-3', memberId: null, memberName: '이준호', memberPhone: '010-2345-6789', memberEmail: 'junho@example.com', memberAddress: '서울시 서초구 방배동 56-7', collectionMode: 'form_input', participatedAt: '2026-03-01T10:00:00Z', hasConsented: true, hasThirdPartyConsented: true, actionType: 'order_click' },
];
