/**
 * 할인 Mock 데이터
 */
import type { Discount } from '@/types/discount';

export const mockDiscounts: Discount[] = [
  {
    id: '1',
    name: '신규가입 할인',
    discountType: 'company',
    method: 'percentage',
    value: 10,
    periodType: 'period',
    target: { type: 'all' },
    applyToAll: true,
    storeIds: [],
    channel: 'all',
    orderType: 'all',
    minOrderAmount: 15000,
    maxDiscountAmount: 5000,
    headquartersRatio: 0,
    franchiseRatio: 100,
    isActive: true,
    usageCount: 152,
    description: '신규 가입 고객 대상 10% 할인',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: '점심 특가',
    discountType: 'company',
    method: 'fixed',
    value: 3000,
    periodType: 'schedule',
    schedule: {
      days: [1, 2, 3, 4, 5],
      timeSlots: [{ startTime: '11:00', endTime: '14:00' }],
    },
    target: { type: 'all' },
    applyToAll: true,
    storeIds: [],
    channel: 'app',
    orderType: 'delivery',
    minOrderAmount: 20000,
    headquartersRatio: 0,
    franchiseRatio: 100,
    isActive: true,
    usageCount: 89,
    description: '평일 점심 시간대 3,000원 할인',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: '주말 할인',
    discountType: 'company',
    method: 'percentage',
    value: 15,
    periodType: 'period',
    startDate: '2024-02-01',
    endDate: '2024-03-31',
    target: { type: 'all' },
    applyToAll: false,
    storeIds: ['store-1', 'store-2'],
    channel: 'all',
    orderType: 'pickup',
    minOrderAmount: 25000,
    maxDiscountAmount: 7500,
    headquartersRatio: 0,
    franchiseRatio: 100,
    isActive: false,
    usageCount: 45,
    description: '주말 주문 시 15% 할인',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: '콜라 1+1 증정',
    discountType: 'gift',
    method: 'percentage',
    value: 0,
    periodType: 'period',
    target: { type: 'all' },
    giftCondition: {
      type: 'n_plus_one',
      buyQuantity: 1,
      getQuantity: 1,
    },
    giftReward: {
      productIds: ['product-cola'],
      quantity: 1,
      maxPerOrder: 2,
    },
    applyToAll: true,
    storeIds: [],
    channel: 'all',
    orderType: 'all',
    headquartersRatio: 0,
    franchiseRatio: 100,
    isActive: true,
    usageCount: 234,
    description: '콜라 1개 구매 시 1개 추가 증정',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
];
