/**
 * 쿠폰 Mock 데이터
 */
import type { Coupon } from '@/types/coupon';

const defaultSchedule = {
  availableDays: [0, 1, 2, 3, 4, 5, 6],
  availableTimeRanges: [{ startTime: '00:00', endTime: '23:59' }],
};

const defaultStoreRestriction = {
  type: 'all' as const,
  storeIds: [] as string[],
};

const defaultSettlementRatio = {
  headquartersRatio: 100,
  franchiseRatio: 0,
};

export const mockCoupons: Coupon[] = [
  {
    id: '1',
    name: '첫 주문 쿠폰',
    description: '첫 주문 고객 대상 20% 할인 쿠폰',
    notice: '다른 쿠폰과 중복 사용 불가',
    discountType: 'percentage',
    discountValue: 20,
    minOrderAmount: 20000,
    maxDiscountAmount: 10000,
    applyScope: 'cart_total',
    orderType: 'all',
    channel: 'all',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    autoDelete: false,
    singleUsePerMember: true,
    totalCount: 1000,
    issuedCount: 580,
    usedCount: 342,
    applicableProductIds: [],
    applicableCategoryIds: [],
    schedule: defaultSchedule,
    storeRestriction: defaultStoreRestriction,
    settlementRatio: defaultSettlementRatio,
    status: 'active',

    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'admin',
  },
  {
    id: '2',
    name: '생일 축하 쿠폰',
    description: '생일 고객 대상 5,000원 할인 쿠폰',
    notice: '생일 당일부터 30일간 사용 가능',
    discountType: 'fixed',
    discountValue: 5000,
    minOrderAmount: 15000,
    maxDiscountAmount: null,
    applyScope: 'cart_total',
    orderType: 'all',
    channel: 'all',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    autoDelete: true,
    singleUsePerMember: true,
    totalCount: 500,
    issuedCount: 210,
    usedCount: 128,
    applicableProductIds: [],
    applicableCategoryIds: [],
    schedule: defaultSchedule,
    storeRestriction: defaultStoreRestriction,
    settlementRatio: defaultSettlementRatio,
    status: 'active',

    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'admin',
  },
  {
    id: '3',
    name: '봄맞이 쿠폰',
    description: '봄 시즌 15% 할인 쿠폰',
    notice: '배달 주문 시에만 사용 가능',
    discountType: 'percentage',
    discountValue: 15,
    minOrderAmount: 25000,
    maxDiscountAmount: 7500,
    applyScope: 'cart_total',
    orderType: 'delivery',
    channel: 'app',
    startDate: '2024-03-01',
    endDate: '2024-05-31',
    autoDelete: false,
    singleUsePerMember: false,
    totalCount: 300,
    issuedCount: 300,
    usedCount: 245,
    applicableProductIds: [],
    applicableCategoryIds: [],
    schedule: defaultSchedule,
    storeRestriction: defaultStoreRestriction,
    settlementRatio: { headquartersRatio: 80, franchiseRatio: 20 },
    status: 'expired',

    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
    createdBy: 'admin',
  },
  {
    id: '4',
    name: 'VIP 전용 쿠폰',
    description: 'VIP 회원 전용 30% 할인',
    notice: 'VIP 등급 회원 전용',
    discountType: 'percentage',
    discountValue: 30,
    minOrderAmount: 30000,
    maxDiscountAmount: 15000,
    applyScope: 'cart_total',
    orderType: 'all',
    channel: 'all',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    autoDelete: true,
    singleUsePerMember: true,
    totalCount: 100,
    issuedCount: 72,
    usedCount: 45,
    applicableProductIds: [],
    applicableCategoryIds: [],
    schedule: defaultSchedule,
    storeRestriction: defaultStoreRestriction,
    settlementRatio: defaultSettlementRatio,
    status: 'active',

    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    createdBy: 'admin',
  },
  {
    id: '5',
    name: 'SNS 프로모션 쿠폰',
    description: 'SNS 프로모션용 3,000원 할인 쿠폰',
    notice: 'SNS 공유 이벤트 전용',
    discountType: 'fixed',
    discountValue: 3000,
    minOrderAmount: 20000,
    maxDiscountAmount: null,
    applyScope: 'cart_total',
    orderType: 'all',
    channel: 'all',
    startDate: '2024-02-01',
    endDate: '2024-06-30',
    autoDelete: false,
    singleUsePerMember: false,
    totalCount: 500,
    issuedCount: 198,
    usedCount: 123,
    applicableProductIds: [],
    applicableCategoryIds: [],
    schedule: defaultSchedule,
    storeRestriction: defaultStoreRestriction,
    settlementRatio: { headquartersRatio: 50, franchiseRatio: 50 },
    status: 'active',

    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    createdBy: 'admin',
  },
];
